var levelPlans = [[
	"                                                                                ",
	"                                                                                ",
	"                                                                                ",
	"                                                       xxx                      ",
	"                             xx!!!xx                  x!!!x       xxxx       x  ",
	"                     xxx      x!!!x                  x!!!!!x                 x  ",
	"                              xxxxx                  xvxvxvx                xx  ",
	"                                                                             x  ",
	"                        xxx                                                  x  ",
	"                                o                                           xx  ",
	"                               xxx                                xxxx       x  ",
	"                                     xx                                      x  ",
	" x                                          xx                              xx  ",
	" x                                                                           x  ",
	" xx                                   xxx                                    x  ",
	"  x                                                                         xx  ",
	"  x                     o                                                    x  ",
	"  x                                    xxxx                                  x  ",
	"  x          xxxx       o                                                    x  ",
	"  x  $       x  x                         =                      xxxxx  o    x  ",
	"  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx      xxxxx     xxxxxxxx  ",
	"                              x   x                  x      x                   ",
	"                              x!!!x                  x!!!!!!x                   ",
	"                              x!!!x                  x!!!!!!x                   ",
	"                              xxxxx                  xxxxxxxx                   ",
	"                                                                                ",
	""
], [
	"                                      x!!x                        xxxxxxx       ",
	"                                      x!!x                     xxxx     xxxx    ",
	"                                      x!!xxxxxxxxxxxx         xx           xx   ",
	"                                      xx!!!!!!!!!!!!x        xx             xx  ",
	"                                       xxxxxxxxxx!!!x                           ",
	"                                         xxxxxxxx!!!x                           ",
	"                                                xx!!x             o   o         ",
	"                                                 x!!x                           ",
	"                                                 xvvx             x   x         ",
	"                                                             xx  |   |   |  xx  ",
	"                                           oo                xx!!!!!!!!!!!xx    ",
	"                                           xx                  xxxx!!!!!xxxx    ",
	"                                            xxx        xx    ! xx  xxxxxxx      ",
	"                                              x        xx  !  xx                ",
	"                                              x        xx !  xx                 ",
	"                                              xxx      xxxxxxx                  ",
	"                                              xx       xx                       ",
	"                                  =           xx      oxx                       ",
	"               xxxxxxx        xxx    xxx      xx      xxx                       ",
	"              xxxxxxxxx         x    x        xx       xx                       ",
	"             xx!!!!!!!!x        x o  x        xxo      xx                       ",
	"     $       xx  v     x        x    x        xxx      xx                       ",
	"    xxx      x         x        x    x        xx       xx                       ",
	"    x x      x       v x       xx o  xx       xx       xx                       ",
	"!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!x       xx                       ",
	"!!!!x x!!!!!!x v       x!!!!!xx       xxxxxxxxxx      xxx                       ",
	"!!!!x x!!!!!!x         x!!!!!x    o       xx            xx                      ",
	"!!!!x x!!!!!!x         x!!!!!x           xx             xxx                     ",
	"!!!!x x!!!!!!x         x!!!!!xx       xxxxx!        xxxxxx                      ",
	"!!!!x x!!!!!!x                        xxxxx!        xxxxx                       ",
	"!!!!x x!!!!!!x                      xxxxx!!!xx      xx                          ",
	"!!!!x x!!!!!!x         x!!!!!!xxxxxxxxxxxxx!       xxxx                         ",
	"!!!!x x!!!!!!x         x!!!!!!        |           xxxxxxx                       ",
	"!!!!x x!!!!!!x         x!!!!!! |                xxx                             ",
	"!!!!x x!!!!!!x                              xxxxx                               ",
	"!!!!x x!!!!!!x                    o       xxxxx                                 ",
	"!!!!x x!!!!!!x    o               o     xxxxx                                   ",
	"!!!!x x!!!!!!x!!!xxx!!!xxxxxxxxxxxxxxxxxxxx                                     "
	
], ];

