var levelPlans = [
	[
		"x ",
		"x            |                        ",
		"x                                     ",
		"x                    xxxxxxxxxxxxx    ",
		"x                                x    ",
		"x                                x    ",
		"x                  $             x    ",
		"xx           xxxxxxxxxxxxx!xxxxx x    ",
		"x                         !!   x x    ",
		"x     x                   !!   xox    ",
		"x                         !!   x x    ",
		"xx             x          !!   x x    ",
		"x         o          x x  !!   xox    ",
		"x         x         xx|xxx!!   x x    ",
		"xxx                       !!xxxx x    ",
		"x                         !!!!!! x    ",
		"x    x        o             o!!!ox    ",
		"x       o    xxx!xx o xxxxxxxxx! x    ",
		"x            x  xxxx xxxxx!!!!!! x    ",
		"x       xx                !!   !o!    ",
		"x                 o       !!   !o!    ",
		"x                xxxxxxxx!!!!  xox    ",
		"x              xx       !!!!!! x x    ",
		"x      o               !!!!!!!!x x    ",
		"x     xxx             !!!!!!!!!x x    ",
		"x                         !!   x x    ",
		"x             o           !!   x x    ",
		"x             x           !!   x x    ",
		"x                         !!   x x    ",
		"x !!!!! x            o    !!   x x  x   xxx x   ",
		"x !   !              x    !!   x x  x   x x x   ",
		"x !                       !!   x x  xxx xxx xxx ",
		"x !          x            !!   x x       ",
		"x                         !!   x x       ",
		"x o x                     !!   x x       ",
		"xxxxx              x      !!   x x       ",
		"x   x   o                 !!   x x       ",
		"x       x                 !!   x x       ",
		"x              x      o   !!   x x       ",
		"x              !          !!   x x       ",
		"x      o              !   !!   x x       ",
		"x                   xx!   !!   x x       ",
		"x      x             !!   !!   x x       ",
		"x      !                  !!   x x       ",
		"x             x           !!   x x       ",
		"x                         !!   x x       ",
		"x                        o!!   xox       ",
		"x          x             x!!x  x x       ",
		"x                       xx!!xx x x       ",
		"x        !xxx!!!xxx!xx!!!!!!xxxxo        ",
		"x   xxx!!!!!!xxxxxxxxxvxxxxxxxxxxxxxxxxxx",
		"xxxx!!!        x  x                      "
	],	
	
	[
	"                                                                                ",
	"                                                                                ",
	"                                                                                ",
	"                                                       xxx                      ",
	"                             xx!!!xx                  x!!!x       xxxx       x  ",
	"                     xxx      x!!!x                  x!!!!!x                 x  ",
	"                              xxxxx                  xvxvxvx                xx  ",
	"                                                                             x  ",
	"                        xxx                                                  x  ",
	"                                o                                           xx  ",
	"                               xxx                                xxxx       x  ",
	"                                     xx                                      x  ",
	" x                                          xx                              xx  ",
	" x                                                                           x  ",
	" xx                                   xxx                                    x  ",
	"  x                                                                         xx  ",
	"                        o                                                    x  ",
	"                                       xxxx                                  x  ",
	"             xxxx       o                                                    x  ",
	"  x  $       x  x                         =                      xxxxx  o    x  ",
	"  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx      xxxxx     xxxxxxxx  ",
	"                              x   x                  x      x                   ",
	"                              x!!!x                  x!!!!!!x                   ",
	"                              x!!!x                  x!!!!!!x                   ",
	"                              xxxxx                  xxxxxxxx                   ",
	"                                                                                ",
	""
], 

[
	"                                      x!!x                        xxxxxxx       ",
	"                                      x!!x                     xxxx     xxxx    ",
	"                                      x!!xxxxxxxxxxxx         xx           xx   ",
	"                                      xx!!!!!!!!!!!!x        xx             xx  ",
	"                                       xxxxxxxxxx!!!x                           ",
	"                                         xxxxxxxx!!!x                           ",
	"                                                xx!!x             o   o         ",
	"                                                 x!!x                           ",
	"                                                 xvvx             x   x         ",
	"                                                             xx  |   |   |  xx  ",
	"                                           oo                xx!!!!!!!!!!!xx    ",
	"                                           xx                  xxxx!!!!!xxxx    ",
	"                                            xxx         x    ! xx  xxxxxxx      ",
	"                                         x    x        xx  !  xx                ",
	"                                              x        xx !  xx                 ",
	"                                        x     xxx      xxxxxxx                  ",
	"                                              xx       xx                       ",
	"                                  =           xx      oxx                       ",
	"               xxxxxxx        xxx    xxx      xx      xxx                       ",
	"              xxxxxxxxx         x    x        xx       xx                       ",
	"             xx!!!!!!!xx        x o xx        xxo      xx                       ",
	"     $       xx  v     x        x    x        xxx      xx                       ",
	"    xxx      x         x        x    x        xx       xx                       ",
	"    x x      x       v x       xx o xx        xx      xxx                       ",
	"!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!x       xx                       ",
	"!!!!x x!!!!!!x v       x!!!!!xx       xxxxxxxxxxx      xx                       ",
	"!!!!x x!!!!!!x         x!!!!!x    ox      xx            xx                      ",
	"!!!!x x!!!!!!x         x!!!!!x          xx             xxx                     ",
	"!!!!x x!!!!!!x         xxvxxvx       xxxxx!        xxxxxx                      ",
	"!!!!x x!!!!!!x                        xxxxx!        xxxxx                       ",
	"!!!!x x!!!!!!x                      xxxxx!!!xx      xx                          ",
	"!!!!x x!!!!!!x         xx xx xxxxxxxxxxxxxx!       xxxx                         ",
	"!!!!x x!!!!!!x         x! xx !x        |           xxxxxxx                       ",
	"!!!!x x!!!!!!x         x! xx !x |                xxx                             ",
	"!!!!x x!!!!!!x                              xxxxx                               ",
	"!!!!x x!!!!!!x                    o       xxxxx                                 ",
	"!!!!x x!!!!!!x    o               o     xxxxx                                   ",
	"!!!!x x!!!!!!x!!!xxx!!!xxxxxxxxxxxxxxxxxxxx                                     "
	
],

];

