var levelPlans = [
	[
		"x ",
		"x            |                        ",
		"x                                     ",
		"x                    xxxxxxxxxxxxx    ",
		"x                                x    ",
		"x                                x    ",
		"x                  $             x    ",
		"xx           xxxxxxxxxxxxx!xxxxx x    ",
		"x                         !!   x x    ",
		"x     x                   !!   xox    ",
		"x                         !!   x x    ",
		"xx             x          !!   x x    ",
		"x         o          x x  !!   xox    ",
		"x         x         xx|xxx!!   x x    ",
		"xxx                       !!xxxx x    ",
		"x                         !!!!!! x    ",
		"x    x        o             o!!!ox    ",
		"x       o    xxx!xx o xxxxxxxxx! x    ",
		"x            x  xxxx xxxxx!!!!!! x    ",
		"x       xx                !!   !o!    ",
		"x                 o       !!   !o!    ",
		"x                xxxxxxxx!!!!  xox    ",
		"x              xx       !!!!!! x x    ",
		"x      o               !!!!!!!!x x    ",
		"x     xxx             !!!!!!!!!x x    ",
		"x                         !!   x x    ",
		"x             o           !!   x x    ",
		"x             x           !!   x x    ",
		"x                         !!   x x    ",
		"x !!!!! x            o    !!   x x  x   xxx x   ",
		"x !   !              x    !!   x x  x   x x x   ",
		"x !                       !!   x x  xxx xxx xxx ",
		"x !          x            !!   x x       ",
		"x                         !!   x x       ",
		"x o x                     !!   x x  xxx     ",
		"xxxxx              x      !!   x x x   x  ",
		"x   x   o                 !!   x x  xxx    ",
		"x       x                 !!   x x       ",
		"x              x      o   !!   x x       ",
		"x              !          !!   x x  x     ",
		"x      o              !   !!   x x  x     ",
		"x                   xx!   !!   x x  xxx     ",
		"x      x             !!   !!   x x       ",
		"x      !                  !!   x x       ",
		"x             x           !!   x x       ",
		"x                         !!   x x       ",
		"x                        o!!   xox       ",
		"x          x             x!!x  x x       ",
		"x                       xx!!xx x x       ",
		"x        !xxx!!!xxx!xx!!!!!!xxxxo        ",
		"x   xxx!!!!!!xxxxxxxxxvxxxxxxxxxxxxxxxxxx",
		"xxxx!!!        x  x                      "
	],	
	
	[
	"                                                                                ",
	"                                                                                ",
	"                                                                                 ",
	"                                                       xxx                       ",
	"                             xx!!!xx                  x!!!x                      ",
	"                              x!!!x                  x!!!!!x                     ",
	"                              xxvxx                  xvxvxvx                   x ",
	"                                                                               x ",
	"                                                                     o         x ",
	"                            o                                        xxxx     x ",
	"                                                                              x",
	" x                         xxx                                                x",
	" x                    o                                                     xxx",
	" xx                                                                       o   x ",   
	"  x           c      xxx                  xxx                                 x",
	"  x     j     o      x x                                                   xxxx",
	"  x                  x x               e                                      x ",
	"  x          xxxx    x x                   o           l                      x    ",
	"  x  $       x  x    x x          =                  =          xxxxxxx    o  x ",
	"  xxxxxxxxxxxx  xxxxxx xxxxxxx    xxxxxxxxxxxxxxxxxxxx      xxxxx     xxxxxxxxx  ",
	"                             x    x                  x      x                   ",
	"                             x!!!!x                  x!!!!!!x                   ",
	"                             x!!!!x                  x!!!!!!x                   ",
	"                             xxxxxx                  xxxxxxxx                   ",
	"                                                                                ",
	""
], 

	[
		"                                      x!!x                        xxxxxxx       ",
		"                                      x!!x                     xxxx     xxxx    ",
		"                                      x!!xxxxxxxxxxxx         xx           xx   ",
		"                                      xx!!!!!!!!!!!!x        xx             xx  ",
		"                                       xxxxxxxxxx!!!x                           ",
		"                                         xxxxxxxx!!!x                           ",
		"                                                xx!!x             o   o         ",
		"                                                 x!!x                           ",
		"                                                 xvvx             x   x         ",
		"                                                             xx  |   |   |  xx  ",
		"                                           oo                xx!!!!!!!!!!!xx    ",
		"                                           xx                !!!xxx!!!!!xxxx    ",
		"                                            xxx         x   !!xx  xxxxxxx      ",
		"                                        xx !!!x        xx   !!xx                ",
		"                                           xx!x        xx!!!!xx                 ",
		"                                      xx     !xxx      xxxxxxx                  ",
		"                                             !xx       xx                       ",
		"                 xxx                =       !!xx      oxx                       ",
		"               xxxxxxx        xxx    xxx   !!!xx      xxx                       ",
		"              xxx!!!xxx         x    x     !!!xx       xx                       ",
		"             xx!!!!!!!xx        x o  x     !!!xxo      xx                       ",
		"     $       xx xvxxx xx        x    x     !!!xxx      xx                       ",
		"    xxx      x         x        x    x     !!!xx       xx                       ",
		"    x x      x       v x       xx o  x    !!!!xx      xxx                       ",
		"!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!xx       xx                       ",
		"!!!!x x!!!!!!x v       x!!!!!xx       xxxx!xxxxxx      xx                       ",
		"!!!!x x!!!!!!x         x!!!!!x    o    xxx!            xx                      ",
		"!!!!x x!!!!!!x         x!!!!!x          xx!         xxxxx                     ",
		"!!!!x x!!!!!!x         xxvxxvx       xxxxx!!    o   xxxxxx                      ",
		"!!!!x x!!!!!!x                        xxxxx!        xxxxx                       ",
		"!!!!x x!!!!!!x                      xxxxx!!!xx      xx                          ",
		"!!!!x x!!!!!!x         xx xx xxxxxxxxxxxxx!!       xxxx                         ",
		"!!!!x x!!!!!!x         xx xx xx        |           xxxx                       ",
		"!!!!x x!!!!!!x         xx xx xx |                xxx                             ",
		"!!!!x x!!!!!!x                               xxxx                               ",
		"!!!!x x!!!!!!x                     o      xxxxx                                 ",
		"!!!!x x!!!!!!x    o                o   xxxxx                                   ",
		"!!!!x x!!!!!!x!!!xxx!!!xxxxxxxxxxxxxxxxxxxx                                     "
		
	],
	[
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"x       !      xx                                x",
	"x $            xx                                x",
	"x       o      xx                                x",
	"xxxxx!xxxxxxx                                    x",
	"x           x  oo  xxxxxxx    xxxxxxxxxxxxxxxxxxxx",          
	"x           x      x                             x",
	"x           x      x                             x",
	"x        |  xxxxxxxx |                           x",
	"x                                                x",
	"x  o                                             x",
	"x    xx                xxx                       x",
	"x     x                x xxxxxxxxxxxxxxxx        x",
	"x     x       =        x x                       x",
	"xxx   xxxxxxxxxxxxxxxxx  x              =        x",
	"x                        x      xxxxxxxxxxxxxxxxxx",
	"x                        x                       x",
	"x            oo          x        =              x",
	"xxx                      xxxxxxxxxxxxxxxxxx    xxx",
	"x        xxxxxxxxx                               x",
	"x                                                x",
	"x                        x     xxxxxxxxxxxxxxxxxxxx",
	"x      xxxxxxxxxxxxxxxxxxx                       x",
	"x      x                            o o          x",
	"x!!!!!!x o                           o           x",
	"x!!!!!!x                                         x",
	"x!!!!!!xxxxx               xxxxxxxxx   xxxxxxx  xx",
	"xxxxxxxx       xxxxxx  xxxxx             x       x",
	"x              x           x             x       x",
	"x   o          x           x             x       x",
	"x  o o    xxxxxxx         xxx   xxxxxxxxxxxxxxxxxx",
	"x         x      x       x x                     x",
	"x         x o     x     x  x                  oo x",
	"x   =     x        !!!!x  x                      x",
	"xxxxxxxxxxxxxx     xxxxxxxxxxxxxx  xxxxxxxxxxxxxxx",
	"x                       x!!!x               !!!!!x",
	"x              xxx    o x!!!x              !!!!!!x",
	"x                xxx    x!!!x             !!!!!!!x",
	"xx      xxxx       xxxxxxxxvxxxxxxxxxx   vxxxxxxxx",
	"x          xx                                    x",
	"x        o xxx                              o    x",
	"x          xxxx                                  x",
	"xx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x",
	"x               |                                x",
	"x                                                x",
	"xxxx                    o o o            |       x",
	"x                       o o o                    x",
	"x        =              =                 =      x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	]
];

